replicaCount: 3

image:
  repository: ghcr.io/sedimentt/book-api
  tag: latest
  pullPolicy: Always

service:
  port: 8080

livenessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3

readinessProbe:
  path: /health
  port: 8080
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 3