global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093
  
scrape_configs:
  - job_name: "book-api"
    static_configs:
      - targets:
          - app:8080
  - job_name: "node-exporter"
    static_configs:
      - targets:
          - node-exporter:9100